### PR TITLE
Suppress erlang:now/0 deprecation warnings

### PR DESCRIPTION
**Pull request by jaydoane**

### CODE REVIEW

**Comment by jaydoane** [comment]
Since the topic is access and creation time comparison for purposes of cache eviction, it doesn't seem important whether or not those values are monotonically increasing, nor particularly accurate. I also noted that `os:timestamp/0` is already used a [couple](https://github.com/apache/couchdb-ets-lru/blob/master/src/ets_lru.erl#L278) [places](https://github.com/apache/couchdb-ets-lru/blob/master/src/ets_lru.erl#L321) in the existing code. However, based on the manual, perhaps we should consistently change them all to `erlang:timestamp/0`?

**Comment by wohali** [comment]
OK, as long as you're sure....

Problem is `erlang:timestamp/0` doesn't show up until Erlang 18, and we still support 17 for now.

**Comment by jaydoane** [comment]
@iilyak you are absolutely correct -- we don't need it at all. While you're here, do you have any opinion on whether it's safe to replace `erlang:now` with `os:timestamp` in those locations?

**Comment by iilyak** [comment]
I don't think changing to `os:timestamp` is safe. We rely on uniqueness of an entry here https://github.com/apache/couchdb-ets-lru/pull/7/files#diff-ec11d0df06913b8bbe0b140772e6f7a4L173

**Comment by eiri** [comment]
I'm with @iilyak - `atime` is a primary key on one of the set tables, it has to be unique, so we'd want to change it not for the `os:timestamp/0`, but for a wrapper similar to `couch_util`'s `unique_monotonic_integer/0`.

A wild idea to get a speed boost would be `os:timestamp/0` with a small random number added to microsecs or even v2 uuid, but I'm not confident about this.

**Comment by wohali** [comment]
@jaydoane if you are eager to push us towards the future, we could raise the minimum version of Erlang to 19 and start using the new functions that guarantee monotonicity.

If you want to make this change (across the board) please start a thread on dev@couchdb.apache.org, this needs at the very least lazy consensus.

**Comment by jaydoane** [comment]
@iilyak @eiri thanks for pointing out that `atime` has to be unique as an ets key, and thus why `os:timestamp/0` would not be safe here. I'll look into doing this with a wrapper as Eric suggests.

I and other Erlang devs would presumably be happy to see OTP 18 as the minimum supported Erlang (@wohali you mentioned 19 in your last message, but I believe it's actually OTP 18 [where the new time functionality was added](http://erlang.org/doc/apps/erts/time_correction.html)). Is the main consideration for this which version gets shipped by major OS vendors? I think at this point just to run the test suite we need OTP 19 for Elixir tests, so perhaps that _is_ a better target than 18?

**Comment by wohali** [comment]
@jaydoane @davisp or @chewbranca told me on IRC that 19 is the minimum for us to start seriously considering `map`s for real use in CouchDB. That's something I think everyone would like to use if possible.

Also, 99% of CouchDB users are installing from our binaries/Docker image, which have Erlang embedded in them. We build these now with [Erlang 19.6.3](https://github.com/apache/couchdb-ci/blob/master/README.md).

So, in reality, just about all users of CouchDB-recent in the pipeline are using 19.

**Comment by jaydoane** [comment]
I tested the most recent change by temporarily adding the `'P'` compiler option to rebar.config and inspecting the resulting `ets_lru.P` file, which showed for OTP 20.3:
```
unique_now() ->
    erlang:timestamp().
```
and for OTP 17.5:
```
unique_now() ->
    now().
```

Unfortunately, it appears that travis builds ets_lru using rebar3, (and also with numerous Erlang version no longer supported in couchdb).

Should we change .travis.yml to match couchdb/.travis.yml's `otp_release` list, and also to use rebar? Or maybe this is a sign that we really should just propose making OTP 19 the minimum required?

**Comment by jaydoane** [comment]
Travis now seems happy, and no more compile warnings. If I can get a +1, I'll squash into a single commit. (I'm also working on an email to dev proposing changing minimum supported version OTP to 19.)

**Comment by eiri** [comment]
@jaydoane But `erlang:timestamp/0` marked as **not** a monotonically increasing time, erlang docs recommend to add `erlang:unique_integer([monotonic])` into the mix to get determined order of events with time of event. http://erlang.org/doc/apps/erts/time_correction.html#how-to-work-with-the-new-api

**Comment by jaydoane** [comment]
Thanks @eiri. Obviously I should not try to read docs (or write code) with a head cold.

Apparently there's no simple drop in replacement for `erlang:now/0` pre OTP 19 that will give the same `{MegaSec, Sec, MicroSec}` time shape and is also guaranteed unique, so AFAICT we would need to change the shape of `atime` everywhere. That would be a lot of work if we also had to maintain OTP 17 compatibility, but fortunately it seems like everyone is pretty on board with the idea of making OTP 19 the minimal version. I'm going to close this PR now, and open a new one using only the new extended time functionality once we no longer have to support pre OTP 19 versions.

**Pull request closed without merging**
